In [1]:
# Update sklearn to prevent version mismatches
!pip install sklearn --upgrade

Requirement already up-to-date: sklearn in c:\users\wl030\anaconda3\lib\site-packages (0.0)
Requirement already satisfied, skipping upgrade: scikit-learn in c:\users\wl030\anaconda3\lib\site-packages (from sklearn) (0.21.3)
Requirement already satisfied, skipping upgrade: scipy>=0.17.0 in c:\users\wl030\anaconda3\lib\site-packages (from scikit-learn->sklearn) (1.2.1)
Requirement already satisfied, skipping upgrade: numpy>=1.11.0 in c:\users\wl030\anaconda3\lib\site-packages (from scikit-learn->sklearn) (1.16.4)
Requirement already satisfied, skipping upgrade: joblib>=0.11 in c:\users\wl030\anaconda3\lib\site-packages (from scikit-learn->sklearn) (0.14.0)

In [2]:
# install joblib. This will be used to save your model. 
# Restart your kernel after installing 
!pip install joblib

Requirement already satisfied: joblib in c:\users\wl030\anaconda3\lib\site-packages (0.14.0)

In [3]:
import pandas as pd

C:\Users\wl030\Anaconda3\lib\site-packages\numpy\core\__init__.py:29: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\wl030\Anaconda3\lib\site-packages\numpy\.libs\libopenblas.BNVRK7633HSX7YVO2TADGR4A5KEKXJAW.gfortran-win_amd64.dll
C:\Users\wl030\Anaconda3\lib\site-packages\numpy\.libs\libopenblas.CSRRD7HKRKC3T3YXA7VY7TAZGLSWDKW6.gfortran-win_amd64.dll
  stacklevel=1)

# Read the CSV and Perform Basic Data Cleaning

In [4]:
df = pd.read_csv("exoplanet_data.csv")
# Drop the null columns where all values are null
df = df.dropna(axis='columns', how='all')
# Drop the null rows
df = df.dropna()
df.head()

,koi_disposition,koi_fpflag_nt,koi_fpflag_ss,koi_fpflag_co,koi_fpflag_ec,koi_period,koi_period_err1,koi_period_err2,koi_time0bk,koi_time0bk_err1,...,koi_steff_err2,koi_slogg,koi_slogg_err1,koi_slogg_err2,koi_srad,koi_srad_err1,koi_srad_err2,ra,dec,koi_kepmag
0,CONFIRMED,0,0,0,0,54.418383,2.479000e-04,-2.479000e-04,162.513840,0.003520,...,-81,4.467,0.064,-0.096,0.927,0.105,-0.061,291.93423,48.141651,15.347
1,FALSE POSITIVE,0,1,0,0,19.899140,1.490000e-05,-1.490000e-05,175.850252,0.000581,...,-176,4.544,0.044,-0.176,0.868,0.233,-0.078,297.00482,48.134129,15.436
2,FALSE POSITIVE,0,1,0,0,1.736952,2.630000e-07,-2.630000e-07,170.307565,0.000115,...,-174,4.564,0.053,-0.168,0.791,0.201,-0.067,285.53461,48.285210,15.597
3,CONFIRMED,0,0,0,0,2.525592,3.760000e-06,-3.760000e-06,171.595550,0.001130,...,-211,4.438,0.070,-0.210,1.046,0.334,-0.133,288.75488,48.226200,15.509
4,CONFIRMED,0,0,0,0,4.134435,1.050000e-05,-1.050000e-05,172.979370,0.001900,...,-232,4.486,0.054,-0.229,0.972,0.315,-0.105,296.28613,48.224670,15.714

# Select your features (columns)

In [5]:
# Set features. This will also be used as your x values.
#selected_features = df[['names', 'of', 'selected', 'features', 'here']]
X = df.drop("koi_disposition",axis=1)
y = df["koi_disposition"]
print(X.shape, y.shape)

(6991, 40) (6991,)

# Create a Train Test Split

Use `koi_disposition` for the y values

In [6]:
X = X.drop(['ra', 'dec','koi_kepmag'], axis=1)

In [7]:
data = y.copy()
data_binary_encoded = pd.get_dummies(data, columns = ["Koi_disposition"])
data_binary_encoded.head()
y =  data_binary_encoded

In [8]:
y.head()

   CANDIDATE  CONFIRMED  FALSE POSITIVE
0          0          1               0
1          0          0               1
2          0          0               1
3          0          1               0
4          0          1               0

In [9]:
y = y.drop(['CANDIDATE'], axis=1)

print(y.shape)

(6991, 2)

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, random_state=1, stratify = y)

In [11]:
X_train.head()

,koi_fpflag_nt,koi_fpflag_ss,koi_fpflag_co,koi_fpflag_ec,koi_period,koi_period_err1,koi_period_err2,koi_time0bk,koi_time0bk_err1,koi_time0bk_err2,...,koi_tce_plnt_num,koi_steff,koi_steff_err1,koi_steff_err2,koi_slogg,koi_slogg_err1,koi_slogg_err2,koi_srad,koi_srad_err1,koi_srad_err2
4838,0,1,1,0,6.279889,0.000007,-0.000007,135.296067,0.000844,-0.000844,...,1,5057,112,-162,3.137,0.435,-0.234,6.222,1.782,-3.310
3004,0,0,0,0,173.257837,0.000817,-0.000817,194.458400,0.003920,-0.003920,...,1,6392,147,-228,4.399,0.057,-0.351,1.162,0.720,-0.131
1585,0,0,0,0,14.796631,0.000126,-0.000126,142.744840,0.006410,-0.006410,...,1,6175,110,-134,4.299,0.072,-0.108,1.307,0.220,-0.135
5085,0,1,0,0,15.713787,0.000001,-0.000001,132.098146,0.000072,-0.000072,...,1,5843,158,-176,4.399,0.124,-0.186,1.006,0.286,-0.154
3758,0,0,0,0,11.570601,0.000118,-0.000118,136.285770,0.008510,-0.008510,...,1,5718,172,-189,4.479,0.078,-0.182,0.900,0.244,-0.105

# Pre-processing

Scale the data using the MinMaxScaler and perform some feature selection

In [12]:
# Scale your data
from sklearn.preprocessing import StandardScaler
X_scaler = StandardScaler().fit(X_train)
#y_scaler = StandardScaler().fit(y_train)

X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)
#y_train_scaled = y_scaler.transform(y_train)
#y_test_scaled = y_scaler.transform(y_test)

In [13]:
print(X_train_scaled.shape,X_test_scaled.shape, y_train.shape,y_test.shape)

(5243, 37) (1748, 37) (5243, 2) (1748, 2)

In [14]:
y_train

      CONFIRMED  FALSE POSITIVE
4838          0               1
3004          0               0
1585          1               0
5085          0               1
3758          0               0
2702          1               0
6978          0               1
3017          1               0
6559          0               1
73            0               1
1817          1               0
6167          0               0
6210          0               1
4893          0               0
1531          0               0
1482          0               1
2730          0               0
5931          0               0
2385          0               1
2915          1               0
3702          0               1
1113          0               0
5267          1               0
354           0               1
3872          0               1
1893          0               0
2516          1               0
5221          0               1
2395          0               1
1126          1               0
...         ...             ...
1146          1               0
6390          0               1
4146          0               1
2185          1               0
3346          0               1
5168          0               1
5613          0               0
2339          1               0
27            1               0
6745          0               1
4690          0               1
1127          1               0
761           0               1
4947          0               1
6012          0               1
1711          0               1
6902          0               0
2018          1               0
2459          1               0
6857          0               1
3084          0               1
3387          1               0
506           1               0
270           1               0
4203          0               1
1776          0               1
1857          0               1
431           0               1
6752          0               0
3930          1               0

[5243 rows x 2 columns]

In [15]:
from sklearn.ensemble import RandomForestClassifier
model3 =RandomForestClassifier(n_estimators=50)
model3 = model3.fit(X_train_scaled,y_train)

# Train the Model

In [16]:
print(f"Training Data Score: {model3.score(X_train_scaled, y_train)}")
print(f"Testing Data Score: {model3.score(X_test_scaled, y_test)}")

Training Data Score: 0.9998092695021934
Testing Data Score: 0.8924485125858124

# Hyperparameter Tuning

Use `GridSearchCV` to tune the model's parameters

In [17]:
# Create the GridSearchCV model
from sklearn.model_selection import GridSearchCV
param_grid = {'n_estimators': [50, 100, 200, 500],
              'max_depth': [10, 50, 100]}
grid3 = GridSearchCV(model3, param_grid, verbose=3)

In [18]:
# Train the model with GridSearch
grid3.fit(X_train_scaled, y_train)

Fitting 3 folds for each of 12 candidates, totalling 36 fits
[CV] max_depth=10, n_estimators=50 ...................................

C:\Users\wl030\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.

[CV] ....... max_depth=10, n_estimators=50, score=0.871, total=   0.7s
[CV] max_depth=10, n_estimators=50 ...................................

[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.6s remaining:    0.0s

[CV] ....... max_depth=10, n_estimators=50, score=0.874, total=   0.9s
[CV] max_depth=10, n_estimators=50 ...................................

[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    1.6s remaining:    0.0s

[CV] ....... max_depth=10, n_estimators=50, score=0.898, total=   0.7s
[CV] max_depth=10, n_estimators=100 ..................................
[CV] ...... max_depth=10, n_estimators=100, score=0.872, total=   1.8s
[CV] max_depth=10, n_estimators=100 ..................................
[CV] ...... max_depth=10, n_estimators=100, score=0.882, total=   1.4s
[CV] max_depth=10, n_estimators=100 ..................................
[CV] ...... max_depth=10, n_estimators=100, score=0.898, total=   1.6s
[CV] max_depth=10, n_estimators=200 ..................................
[CV] ...... max_depth=10, n_estimators=200, score=0.875, total=   3.1s
[CV] max_depth=10, n_estimators=200 ..................................
[CV] ...... max_depth=10, n_estimators=200, score=0.884, total=   3.0s
[CV] max_depth=10, n_estimators=200 ..................................
[CV] ...... max_depth=10, n_estimators=200, score=0.896, total=   3.4s
[CV] max_depth=10, n_estimators=500 ..................................
[CV] ...... max_depth=10, n_estimators=500, score=0.878, total=   7.9s
[CV] max_depth=10, n_estimators=500 ..................................
[CV] ...... max_depth=10, n_estimators=500, score=0.885, total=   7.7s
[CV] max_depth=10, n_estimators=500 ..................................
[CV] ...... max_depth=10, n_estimators=500, score=0.898, total=   7.9s
[CV] max_depth=50, n_estimators=50 ...................................
[CV] ....... max_depth=50, n_estimators=50, score=0.874, total=   0.9s
[CV] max_depth=50, n_estimators=50 ...................................
[CV] ....... max_depth=50, n_estimators=50, score=0.883, total=   0.9s
[CV] max_depth=50, n_estimators=50 ...................................
[CV] ....... max_depth=50, n_estimators=50, score=0.897, total=   1.2s
[CV] max_depth=50, n_estimators=100 ..................................
[CV] ...... max_depth=50, n_estimators=100, score=0.883, total=   1.8s
[CV] max_depth=50, n_estimators=100 ..................................
[CV] ...... max_depth=50, n_estimators=100, score=0.884, total=   2.1s
[CV] max_depth=50, n_estimators=100 ..................................
[CV] ...... max_depth=50, n_estimators=100, score=0.902, total=   1.8s
[CV] max_depth=50, n_estimators=200 ..................................
[CV] ...... max_depth=50, n_estimators=200, score=0.884, total=   4.1s
[CV] max_depth=50, n_estimators=200 ..................................
[CV] ...... max_depth=50, n_estimators=200, score=0.886, total=   4.1s
[CV] max_depth=50, n_estimators=200 ..................................
[CV] ...... max_depth=50, n_estimators=200, score=0.898, total=   3.8s
[CV] max_depth=50, n_estimators=500 ..................................
[CV] ...... max_depth=50, n_estimators=500, score=0.884, total=  10.0s
[CV] max_depth=50, n_estimators=500 ..................................
[CV] ...... max_depth=50, n_estimators=500, score=0.888, total=   9.9s
[CV] max_depth=50, n_estimators=500 ..................................
[CV] ...... max_depth=50, n_estimators=500, score=0.901, total=   9.9s
[CV] max_depth=100, n_estimators=50 ..................................
[CV] ...... max_depth=100, n_estimators=50, score=0.879, total=   0.9s
[CV] max_depth=100, n_estimators=50 ..................................
[CV] ...... max_depth=100, n_estimators=50, score=0.884, total=   0.9s
[CV] max_depth=100, n_estimators=50 ..................................
[CV] ...... max_depth=100, n_estimators=50, score=0.893, total=   1.2s
[CV] max_depth=100, n_estimators=100 .................................
[CV] ..... max_depth=100, n_estimators=100, score=0.883, total=   1.8s
[CV] max_depth=100, n_estimators=100 .................................
[CV] ..... max_depth=100, n_estimators=100, score=0.885, total=   2.1s
[CV] max_depth=100, n_estimators=100 .................................
[CV] ..... max_depth=100, n_estimators=100, score=0.900, total=   2.0s
[CV] max_depth=100, n_estimators=200 .................................
[CV] ..... max_depth=100, n_estimators=200, score=0.886, total=   3.8s
[CV] max_depth=100, n_estimators=200 .................................
[CV] ..... max_depth=100, n_estimators=200, score=0.888, total=   3.9s
[CV] max_depth=100, n_estimators=200 .................................
[CV] ..... max_depth=100, n_estimators=200, score=0.903, total=   4.0s
[CV] max_depth=100, n_estimators=500 .................................
[CV] ..... max_depth=100, n_estimators=500, score=0.883, total=   9.9s
[CV] max_depth=100, n_estimators=500 .................................
[CV] ..... max_depth=100, n_estimators=500, score=0.886, total=  10.1s
[CV] max_depth=100, n_estimators=500 .................................
[CV] ..... max_depth=100, n_estimators=500, score=0.899, total=  10.1s

[Parallel(n_jobs=1)]: Done  36 out of  36 | elapsed:  2.4min finished

GridSearchCV(cv='warn', error_score='raise-deprecating',
             estimator=RandomForestClassifier(bootstrap=True, class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features='auto',
                                              max_leaf_nodes=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              n_estimators=50, n_jobs=None,
                                              oob_score=False,
                                              random_state=None, verbose=0,
                                              warm_start=False),
             iid='warn', n_jobs=None,
             param_grid={'max_depth': [10, 50, 100],
                         'n_estimators': [50, 100, 200, 500]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=3)

In [19]:
print(grid3.best_params_)
print(grid3.best_score_)

{'max_depth': 100, 'n_estimators': 200}
0.8920465382414648

# Save the Model

In [20]:
# save your model by updating "your_name" with your name
# and "your_model" with your model variable
# be sure to turn this in to BCS
# if joblib fails to import, try running the command to install in terminal/git-bash
import joblib
filename = 'best_model.sav'
joblib.dump(grid3, filename)

['best_model.sav']